USE QUANLYSINHVIEN
DELETE DANGKYHOC
SELECT *FROM DANGKYHOC


INSERT INTO DANGKYHOC(MASV,MAMON,HOCKY)
VALUES ('K6100001','GT1',1)
INSERT INTO DANGKYHOC(MASV,MAMON,HOCKY)
VALUES ('K6100001','HH',2)
INSERT INTO DANGKYHOC(MASV,MAMON,HOCKY)
VALUES ('K6100002','DSTT',1)
INSERT INTO DANGKYHOC(MASV,MAMON,HOCKY)
VALUES ('K6100002','GT1',1)
INSERT INTO DANGKYHOC(MASV,MAMON,HOCKY)
VALUES ('K6100003','HH',1)
SELECT MAMON FROM SINHVIEN SV ,DANGKYHOC DKH WHERE  SV.MASV = DKH.MASV AND HOTEN = N'NGUYỄN THỊ HOÀI'
SELECT SV.HOTEN,SV.MASV,KH.TENKHOA FROM SINHVIEN SV  ,DANGKYHOC DKH , MONHOC MH , KHOA KH WHERE
 SV.MASV = DKH.MASV AND DKH.MAMON = MH.MAMON AND MH.TENMON =N'GIẢI TÍCH 1' AND DKH.HOCKY = 1 AND SV.MAKHOA = KH.MAKHOA;

SELECT SV.HOTEN,SV.MASV,SV.NGAYSINH , KH.TENKHOA   FROM SINHVIEN SV , KHOA KH WHERE SV.MAKHOA = KH.MAKHOA ORDER BY KH.TENKHOA ,SV.HOTEN;

SELECT COUNT(SV.MASV) AS SL ,KH.MAKHOA FROM SINHVIEN SV,KHOA KH WHERE SV.MAKHOA = KH.MAKHOA GROUP BY KH.MAKHOA;

SELECT MH.TENGV , DKH.HOCKY  FROM MONHOC MH , DANGKYHOC DKH WHERE MH.MAMON = DKH.MAMON 


UPDATE DANGKYHOC SET MAMON ='GT1' , HOCKY = 2 WHERE  MAMON ='GT1' AND HOCKY = 1


DELETE FROM MONHOC  WHERE  MAMON IN (SELECT MAMON FROM DANGKYHOC WHERE TENGV =N'ĐỖ ĐỨC THÁI' AND HOCKY =2);


SELECT COUNT(DKH.MAMON) AS SL  FROM DANGKYHOC DKH WHERE DKH.HOCKY = 1;