create database QLBongda

use QLBongda


create table CAUTHU
(
MACT NUMERIC NOT NULL,
HOTEN NVARCHAR(100) NOT NULL,
VITRI NVARCHAR(20) NOT NULL,
NGAYSINH DATETIME NULL,
DIACHIA NVARCHAR(200) NOT NULL,
MACLB VARCHAR (5) NOT NULL,
MAQG VARCHAR (5) NOT NULL,
SO INT NOT NULL,

CONSTRAINT PK_MACT PRIMARY KEY (MACT),



)

ALTER TABLE CAUTHU ADD CONSTRAINT FK_MAQG_CAUTHU FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG) ON DELETE CASCADE  ON UPDATE CASCADE

CREATE TABLE QUOCGIA
(
MAQG VARCHAR(5) NOT NULL,
TENQG NVARCHAR (60) NOT NULL,
CONSTRAINT PK_MAqg PRIMARY KEY (MAQG),

)

CREATE TABLE CAULACBO

(
MACLB VARCHAR(5) NOT NULL,
TENCLB NVARCHAR (100) NOT NULL,
MASAN VARCHAR (5) NOT NULL,
MATINH VARCHAR(5) NOT NULL,

CONSTRAINT PK_MACLB PRIMARY KEY (MACLB)


)
ALTER TABLE CAULACBO ADD CONSTRAINT PK_MATINH_CLB FOREIGN KEY(MATINH) REFERENCES  TINH(MATINH) ON DELETE CASCADE ON UPDATE CASCADE 
CREATE TABLE TINH 
(
MATINH VARCHAR(5) NOT NULL,
TENTINH NVARCHAR(100) NOT NULL,

CONSTRAINT PK_TINH PRIMARY KEY (MATINH),

)
--ALTER TABLE TINH ADD CONSTRAINT PK_MSAN_SANVD FOREIGN KEY(MASAN) REFERENCES SANVD(MASAN) ON DELETE CASCADE ON UPDATE CASCADE 
 CREATE TABLE SANVD
 (
 MASAN VARCHAR (5) NOT NULL ,
 TENSAN NVARCHAR(100) NOT NULL,
 DIACHI NVARCHAR (200)NULL,

 CONSTRAINT PK_MASAN PRIMARY KEY (MASAN)

 
 )

 CREATE TABLE HUANLV 
 (
 
 MAHLV VARCHAR(5) NOT NULL,

 TENHLV NVARCHAR (100) NOT NULL,
 NGAYSINH DATETIME ,
 DIACHI NVARCHAR (200) NULL,
 DIENTHOAI NVARCHAR (20) NULL,
 MAQG VARCHAR(5) NOT NULL,

 CONSTRAINT PK_TENHLV PRIMARY KEY (TENHLV),

 
 )
 ALTER TABLE HUANLV ADD CONSTRAINT FK_MQG FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG) ON DELETE CASCADE ON UPDATE CASCADE
 ALTER TABLE HUANLV ADD CONSTRAINT FK_HLVCLB FOREIGN KEY (MAHLV) REFERENCES HLV_CLB(MAHLV) ON DELETE CASCADE 
 CREATE TABLE HLV_CLB
 (
 MAHLV VARCHAR(5) NOT NULL,
 MACLB VARCHAR(5) NOT NULL,
 VAITRO NVARCHAR(100) NOT NULL,

 CONSTRAINT PK_MAHLV_VAITRO PRIMARY KEY (MAHLV , VAITRO)

 
 )

 
 CREATE TABLE TRANDAU
 (
  MATRAN NUMERIC NOT NULL,
  NAM INT NOT NULL,
  VONG INT NOT NULL,
  NGAYTD DATE NOT NULL,
  MACLB VARCHAR(5) NOT NULL,
  MASAN VARCHAR (5) NOT NULL,
  KETQUA VARCHAR (5) NOT NULL, 
  CONSTRAINT PK_MATRAN PRIMARY KEY (MATRAN),

 
 )
 CREATE TABLE BANGXH (
    MACLB VARCHAR(5),
    NAM INT NOT NULL,
    VONG INT NOT NULL,
    SOTRAN INT NOT NULL,
    THANG INT NOT NULL,
    HOA INT NOT NULL,
    THUA INT NOT NULL,
    HIEUSO INT NOT NULL,
    DIEM INT NOT NULL,
    HANG INT NOT NULL,
   CONSTRAINT PK_MACLB_NAM_VONG PRIMARY KEY (MACLB, NAM, VONG),
	)

