Create database QLGiangDay

Use QLGiangDay



Create Table GIAOVIEN
(
MaGV Varchar(20) NOT NULL,
HoTen Nvarchar(50)NOT Null,
MaKhoa VarChar(30) NOT NULL,
Constraint PK_MAGV PRIMARY KEY(MaGV),
Constraint FK_MAKHOA_GV FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa) ON DELETE CASCADE  ON UPDATE CASCADE
)

CREATE Table KHOA
(

MaKhoa Varchar(30) NOT NULL,
TENKHOA VARCHAR(50) NOT NULL,
Constraint PK_MAKHOA PRIMARY KEY(MaKhoa),


)

Create Table MONHOC
(
MaMH Varchar(20) Not Null,
TenMH NVARCHAR(30) Not NULL,
Constraint PK_MAMH PRIMARY KEY(MaMH),



)

Create Table PHONGHOC
(
PHONG Varchar(10) Not NULL,
CHUCNANG Varchar(20) NOT NULL,

CONSTRAINT PK_PHONG PRIMARY KEY (PHONG)


)
CREATE TABLE LOP
(

MALOP VARCHAR(20) NOT NULL,
TENLOP VARCHAR(20) NOT NULL,
MaKhoa Varchar(30) not null,

CONSTRAINT PK_MALOP PRIMARY KEY (MALOP),
CONSTRAINT FK_MAKHOA_LOP FOREIGN KEY  (MaKhoa) REFERENCES Khoa(MaKhoa) ON DELETE CASCADE ON UPDATE CASCADE 
)


ALTER TABLE GIAOVIEN
ADD NGAYSINH DATETIME,
    GIOITINH BIT,
    TUOI INT;


	ALTER TABLE PHONGHOC ADD SUCCHUA INT;
	ALTER TABLE MONHOC ADD SOTC INT , TCLT INT , TCTH INT ;
	ALTER TABLE LOP ADD SISO INT;
	
ALTER TABLE MONHOC
ADD CONSTRAINT CK_TCLT CHECK (TCLT >= 0),
CONSTRAINT CK_STC CHECK (SOTC >= 0),
 CONSTRAINT CK_TCTH CHECK (TCTH >=0);

 ALTER TABLE LOP
 ADD CONSTRAINT CK_SISO CHECK ( SISO >=0);


 ALTER TABLE PHONGHOC
 ADD CONSTRAINT CK_SUCCHUA CHECK(SUCCHUA >=0);

 ALTER TABLE GIAOVIEN
 ADD CONSTRAINT CK_TUOIGV CHECK (TUOI >= 22);
