CREATE DATABASE QLYHANGHOA
USE QLYHANGHOA

CREATE TABLE KHACHHANG 
(
MAKH CHAR(4) NOT NULL , 
HOTEN VARCHAR(40) NOT NULL, 
DCHI VARCHAR(50) NOT NULL,
SODT VARCHAR (20) NOT NULL,
NGSINH SMALLDATETIME NOT NULL,
NGDK SMALLDATETIME NOT NULL,
DOANHSO MONEY NOT NULL, 
CONSTRAINT PK_MAKH PRIMARY KEY (MAKH)

)


CREATE TABLE NHANVIEN
(

MANV CHAR(4) NOT NULL,
HOTEN VARCHAR(40) NOT NULL,
SODT VARCHAR(20) NOT NULL,
NGVL SMALLDATETIME,
CONSTRAINT PK_MANV PRIMARY KEY (MANV)


)

CREATE TABLE SANPHAM
(
MASP CHAR(4) NOT NULL,
TENSP VARCHAR(40) NOT NULL,
DVT VARCHAR(20) NOT NULL,
NUOCSX VARCHAR(40) NOT NULL,
GIA MONEY NOT NULL,
CONSTRAINT PK_MASP PRIMARY KEY (MASP)

)
CREATE TABLE HOADON
(
SOHD INT NOT NULL,
NGHD SMALLDATETIME NOT NULL,
MAKH CHAR(4) NOT NULL,
MANV CHAR(4) NOT NULL,
TRIGIA MONEY NOT NULL,
CONSTRAINT PK_SOHD PRIMARY KEY (SOHD) ,
CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE ON UPDATE CASCADE
)
CREATE TABLE CTHD
(
  SOHD INT NOT NULL,
MASP CHAR(4) NOT NULL,
SL INT NOT NULL,
CONSTRAINT PK_SOHD_MASP PRIMARY KEY (SOHD,MASP),
CONSTRAINT FK_CTHD_ FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_CTHD_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) ON DELETE CASCADE ON UPDATE CASCADE

)






ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)
ALTER TABLE KHACHHANG ADD  LOAIKH TINYINT

ALTER TABLE  SANPHAM ALTER  COLUMN  GHICHU VARCHAR(100) 


ALTER TABLE SANPHAM DROP COLUMN GHICHU



ALTER TABLE KHACHHANG ADD CONSTRAINT VANGLAI CHECK (LOAIKH='VANG LAI' OR LOAIKH = 'THUONG XUYEN' OR LOAIKH = 'VIP')
ALTER TABLE SANPHAM ADD CONSTRAINT DONVITINH CHECK (DVT IN ('CAY','HOP','CAI','QUYEN','CHUC'))
ALTER TABLE SANPHAM ADD CONSTRAINT GIA CHECK (DVT >=500)

ALTER TABLE SANPHAM ADD CONSTRAINT MASP CHECK( MASP>=1)

ALTER TABLE KHACHHANG ADD CONSTRAINT DANGKI_1 CHECK(NGDK  - NGSINH >0)

ALTER TABLE HOADON
ADD CONSTRAINT Check_NGHD_NGDK
CHECK (NGHD >= (SELECT NGDK FROM KHACHHANG WHERE KHACHHANG.MAKH = HOADON.MAKH));

