

CREATE TABLE HOCSINH (
    
    ten VARCHAR(255) NOT NULL,
    tuoi INT NOT NULL,
	lop VARCHAR(20)NOT NULL,
);


CREATE TABLE DIEM
(
	TOAN INT ,
	VAN INT ,
	NGOAINGU INT,
	NAME NVARCHAR(100),
	NGAYSINH DATE
);
ALTER TABLE DIEM
ADD  NGAYSINH DATE;
GO 
INSERT INTO DIEM (TOAN, VAN, NGOAINGU, NAME, NGAYSINH)
VALUES (10, 10, 10, 'PHẠM NGUYÊN', '2004-11-25');


